config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :mascots

end

app/models/mascot.rb
class Mascot < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mascots_controller.rb
class MascotsController < ApplicationController

  def index
    @mascot = Mascot.new
    @mascots = Mascot.all
  end

  def create
    @mascot = Mascot.new(mascot_params)
    if @mascot.save

      redirect_to mascots_path
    else
      render :index
    end
  end

  def show
    @mascot = Mascot.find(params[:id])
  end

  def edit
    @mascot = Mascot.find(params[:id])
  end

  def update
    @mascot = Mascot.find(params[:id])
    @mascot.update_attributes!(mascot_params)

    redirect_to mascots_path
  end

  def destroy
    @mascot = Mascot.find(params[:id]).delete

    redirect_to mascots_path
  end

  private
  def mascot_params
    params.require(:mascot).permit(:company, :company_mascot)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudMascots</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mascots/edit.html.erb
<%= form_for @mascot do |f| %>
  <p>
    <%= f.label :company %>
    <%= f.text_field :company %>
  </p>
  <p>
    <%= f.label :company_mascot %>
    <%= f.text_field :company_mascot %>
  </p>
  <p>
    <%= f.submit 'Update mascot' %>
  </p>
<% end %>

app/views/mascots/index.html.erb
<%= form_for @mascot do |f| %>
<p>
  <%= f.label :company %>
  <%= f.text_field :company %>
</p>
  <p>
    <%= f.label :company_mascot %>
    <%= f.text_field :company_mascot %>
  </p>
  <p>
    <%= f.submit 'Add mascot' %>
  </p>
<% end %>

<%= @mascots.each do |mascot| %>
<ul>
  <li>
    <%= link_to "#{mascot.company}", mascot_path(mascot) %>, <%= mascot.company_mascot %>
  </li>
</ul>
<% end %>

app/views/mascots/show.html.erb
<ul>
  <li>
    <%= @mascot.company %>, <%= @mascot.company_mascot %>
  </li>
</ul>

<%= link_to 'Edit', edit_mascot_path %>
<%= link_to 'Delete', mascot_path(@mascot), method: :delete %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to 'Add a mascot', mascots_path %>